### ISSUE TITLE
Updata from prevous version of stream-fusion docker compose

### ISSUE THREAD

**Issue by ericvlog** [LimeDrive/stream-fusion#53]
hello, i long time using stream-fusion. before my compose file is 

```
services:
  stream-fusion:
    image: ghcr.io/limedrive/stream-fusion:latest
    container_name: stream-fusion
    environment:
      SECRET_API_KEY: 'dfsdfsdfsdfs1d-4a8c-84ac-cfa47a7fa79f'
      TMDB_API_KEY: 'b9dsfsdfsdfsf4670f7a67d5e8c5f9'
      FLARESOLVERR_HOST: http://192.168.1.100:8191
      JACKETT_HOST: 192.168.1.100
      JACKETT_PORT: 9117
      JACKETT_SHEMA: http
      JACKETT_API_KEY: 'tpk4t3g1ddfdfdfdp08lz5kahfcbc6p'
      USE_HTTPS: True
      ZILEAN_URL: http://192.168.1.13:8181
      ZILEAN_POOL_CONNECTIONS: 20
      ZILEAN_API_POOL_MAXSIZE: 20
      REDIS_HOST: redis
      REDIS_PORT: 6379
      LOG_LEVEL: DEBUG
      LOG_REDACTED: False
#      USE_HTTPS: True
      TZ: Asia/Kuala_Lumpur
    ports:
      - 8080:8080
    volumes:
      - /mnt/hd/stream-fusion:/app/config
#    depends_on:
#      elasticsearch:
#        condition: service_healthy
#      redis
#      - zilean
#      - jackett
#      - flaresolverr
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    expose:
      - 6379
    volumes:
      - /mnt/hd/stream-fusion/redis:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
```
after pull the latest images it say sleeping due to postgress .....
i have zilean , jackett in other docker, and i dun want use warp.

how i intergrade above compose with new stream-fusion.
Thanks.

**Comment by LimeDrive** [comment]
Hello, 

v2 introduce breaking change : https://github.com/LimeDrive/stream-fusion/releases/tag/v2.0.0

you will need to update your install, please check the doc : https://docs.stremio-stack.com/en/StreamFusion/docker_install/

**Comment by ericvlog** [comment]
if I already have zilean & jackett and dun need warp, then just remove these  ?

**Comment by ericvlog** [comment]
```
version: '2.4'

networks:
  proxy_network:
    external: true

services:

  stream-fusion:
    image: ghcr.io/limedrive/stream-fusion:latest
    container_name: stream-fusion
    environment:
      SECRET_API_KEY: '<your_secret_api_key>'
      TMDB_API_KEY: '<your_tmdb_api_key>'
      REDIS_HOST: stremio-redis
      PG_HOST: stremio-postgres
      PG_USER: '<your_postgres_user>'
      PG_PASS: '<your_postgres_password>'
      USE_HTTPS: True
      TZ: Asia/Kuala_Lumpur
    ports:
      - "8080:8080"  # Host port:Container port
    expose:
      - 8080
    volumes:
      - ./stream-fusion:/app/config
    depends_on:
      - stremio-postgres
      - stremio-redis
    restart: unless-stopped
    networks:
      - proxy_network

  stremio-redis:
    image: redis:latest
    container_name: stremio-redis
    expose:
      - 6379
    volumes:
      - ./stremio-redis:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - proxy_network

  stremio-postgres:
    image: postgres:16.3-alpine3.20
    container_name: stremio-postgres
    restart: unless-stopped
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: '<your_postgres_user>'
      POSTGRES_PASSWORD: '<your_postgres_password>'
      POSTGRES_DB: stream_fusion_db
    expose:
      - 5432
    volumes:
      - ./stremio-postgres:/var/lib/postgresql/data/pgdata
    networks:
      - proxy_network

volumes:
  stremio-postgres:
  stremio-redis:
  stream-fusion:
  ```
  Now can need add `    ports:
      - "8080:8080"  # Host port:Container port`
